(setq notmuch-folders '(("inbox"           . "tag:inbox")
                        ("unread"          . "tag:unread")
                        ("apt-listchanges" . "tag:apt-listchanges")
                        ("awesome"         . "tag:awesome")
                        ("awesome-devel"   . "tag:awesome-devel")
                        ("chewing"         . "tag:chewing")
                        ("chewing-devel"   . "tag:chewing-devel")
                        ("dot"             . "tag:dot")
                        ("hackingthursday" . "tag:hackingthursday")
                        ("hojia"           . "tag:hojia")
                        ("lug"             . "tag:lug")
                        ("mew-int"         . "tag:mew-int")
                        ("pcmanx"          . "tag:pcmanx")
                        ("0xlab"           . "tag:0xlab")
                        ("madbutterfly"    . "tag:madbutterfly")
                        ("notmuch"         . "tag:notmuch")
                        ))

