(require 'notmuch)
(setq notmuch-folders '(("inbox"           . "tag:inbox")
                        ("unread"          . "tag:unread")
                        ("apt-listchanges" . "tag:apt-listchanges")
                        ("awesome"         . "tag:awesome")
                        ("awesome-devel"   . "tag:awesome-devel")
                        ("chewing"         . "tag:chewing")
                        ("chewing-devel"   . "tag:chewing-devel")
                        ("dot"             . "tag:dot")
                        ("hackingthursday" . "tag:hackingthursday")
                        ("hojia"           . "tag:hojia")
                        ("lug"             . "tag:lug")
                        ("mew-int"         . "tag:mew-int")
                        ("pcmanx"          . "tag:pcmanx")
                        ("0xlab"           . "tag:0xlab")
                        ("madbutterfly"    . "tag:madbutterfly")
                        ("notmuch"         . "tag:notmuch")
                        ("emacs-devel"     . "tag:emacs-devel")
                        ))

(defun notmuch-mark-as-spam ()
  (interactive)
  (notmuch-call-notmuch-process "tag" "-unread" "-inbox" "+spam"
                                (notmuch-search-find-thread-id)
                                "and"
                                notmuch-search-query-string))